### ISSUE TITLE
Examples of how to use RZCollectionTableView component

### ISSUE THREAD

**Issue by pandaduc** [Raizlabs/RZUtils#119]
Hi,

I'm wondering if there's any example of using RZCollectionTableView component. I'm still newbie to iOS, I was trying to implement "Swipe to delete" for UICollectionView displaying item as List View which similar to UITableView.

Thank you so much.

**Comment by adamhrz** [comment]
Hi @pandaduc thanks for asking - we're working on documenting each component of the RZUtils library and adding a catalog app demoing each piece. RZCollectionTableView is quite a common component so is high on our list of priorities for the documentation process.  Are you still battling through this?

**Comment by pandaduc** [comment]
Hi @adamhrz , thank you for your reply. I didn't use RZCollectionTableView for my project for now as I couldn't figure out how to implement it. However, I converted the UICollectionView to UITableView to get benefit of native "Swipe to delete" functionality. But I still would love to know how to implement RZCollectionTableView, so I'm still curious about your future updates for the documentation of RZUtilities. Thanks.

**Comment by mohshin-shah** [comment]
@adamhrz ,i am also having the same dillema to add the swipe functionality add custom views on the left or right side of the UIcollectionviewcell.Please let me know if we can achieve this using RZComponents.Thanks :) :+1:

**Comment by davidneal-raizlabs** [comment]
I am currently working on sample code for RZCollectionTableView. The sample code has swipe-to-edit functionality as well as a RZCollectionTableViewCell with embedded views. 

Would you like to be the first person to try out this code. I would be interested in your feedback as to whether the demo shows you how to implement the functionality you are interested in.

David

**Comment by mohshin-shah** [comment]
Yes, i want to try out the code.Can u please send me.I have done with the editing mode with custom views.Still there's small issue.that is dequeueing the cells while we scroll down and get back on the previous portion of UIscrollview. 
yOu can send me the code on mohshinshah@hotmail.com.

**Comment by alexandre-g** [comment]
@davidneal-raizlabs Hey, thanks for all the great work.
I wouldn't mind the code either - would help a lot. Trying to integrate this component into project at this moment. alexandre аt goloskok dot com. Cheers

**Comment by arrouse** [comment]
Hey @alexandre-g you can check out David's code here https://github.com/Raizlabs/RZCollectionTableView/tree/feature/dneal/sample-code  It will soon get merged into Develop on that repo, but you can look at it there for now.

**Comment by IfyNdu** [comment]
Hi guys, 

Demo project written in swift by any chance?

**Comment by ZevEisenberg** [comment]
@IfyNdu thanks for writing in. Unfortunately, we've mostly stopped using RZUtils since our development team has transitioned to Swift, so we don't have a lot of time to put into RZUtils or RZCollectionList. I don't think we are ever going to make a Swift demo project. Is there a particular component you're having trouble with?

**Comment by IfyNdu** [comment]
@ZevEisenberg Thanks for the reply. All I need for now is to get the CollectionTableView to work with my existing Collection view. So far i've only managed to achieve this much since I posted my initial comment.

<img width="330" alt="screen shot 2017-05-26 at 20 51 29" src="https://cloud.githubusercontent.com/assets/15639127/26510427/35983cc0-4255-11e7-8f20-4594aca7e4f7.png">

For some reason none of the delegates are fired.

**Comment by IfyNdu** [comment]
Problem solved!
